---
version: '3.9'

networks:
    fle_net: {}
    dat_net: {}
    svc_net: {}

services:
    db:
        image: postgres:13.3
        environment:
            POSTGRES_USER: pastr
            POSTGRES_PASSWORD: pastr
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data
        networks:
            - dat_net
    s3:
        image: minio/minio
        command: server /data
        ports:
            - 9000:9000
        volumes:
            - /data
        networks:
            - fle_net
    nginx:
        image: nginx
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - /data/nginx/cache
        ports:
            - 8000:80
        networks:
            - svc_net
