---
version: '3.9'

services:
    db:
        image: postgres:13.3
        environment:
            POSTGRES_USER: paste
            POSTGRES_DATABASE: paste
            POSTGRES_PASSWORD: paste
        ports:
            - '5432:5432'
        volumes:
            - /var/lib/postgresql/data
    redis:
        image: redis:6.2.3
        ports:
            - 6379:6379
